OOP school library: add Person, Student and Teacher classes
berylcl/OOP-school-library pull request #1
Opened 2023-07-25 21:00 UTC by berylcl

In this PR, I included
  - Create class Person with the following:
       - Instance vars: @id, @name, and @age.
       - Constructor with name, age, and parent_permission as parameter. name and parent_permission are optional and have default values of "Unknown" and true.
      -  Getters for @id, @name, and @age.
      -  Setters for @name and @age.
       - Private method of_age? that returns true if @age is greater or equal to 18 and false otherwise.
       - Public method can_use_services? that returns true if person is of age or if they have permission from parents.
 - Create class Student with the following:
       - Inherits from Person.
       - Constructor extends parent's constructor by adding @classroom and a parameter for it.
       - Method play_hooky that returns "¯\(ツ)/¯".
-  Create class Teacher with the following:
       - Inherits from Person.
       - Constructor extends parent's constructor by adding @specialization and a parameter for it.
      -  Override can_use_services? so it always returns true.

2023-07-25 22:03 UTC, Owusu-Desmond requested changes
Hi @berylcl , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 22:03 UTC, Owusu-Desmond commented on person.rb
> +
- [ ] Please make sure that the `:name` and `:age` instance variables should be able to be modified so I suggest they are defined as attr_accessors (both Getters and Setters are defined) :pray:

2023-07-25 22:03 UTC, Owusu-Desmond commented on person.rb
> +end
- [ ] From the project requirement, you should create a public method `can_use_services?` that returns true if the person is of age or if they have permission from parents :blush:

2023-07-25 22:03 UTC, Owusu-Desmond commented on README.md
> +
- [ ] You have the`setup` section repeated in your readme file so make sure you remove one to make your readme file professional :blush:

2023-07-25 22:03 UTC, Owusu-Desmond commented on README.md
> +## 👤 Author <a name="author"></a>
- [ ] You have the`Author` section repeated in your readme file so make sure you remove one to make your readme file professional :blush:

2023-07-27 05:41 UTC, tresorsawasawa approved these changes
# STATUS: APPROVE :heavy_check_mark: :heavy_check_mark:  :champagne: 

Hi @berylcl 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://camo.githubusercontent.com/aced9b1ffa1374fee6c3bcb9689701088f26a09dc5e75eaa59a01fd38ccc26f2/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f766d74786e78766556556f64472f67697068792e676966)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 

## Optional suggestions
_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 05:41 UTC, merged